### ISSUE TITLE
Update CoreHunter Facade

### ISSUE THREAD

**Issue by daveneti** [corehunter/corehunter3#44]
Refactor old CoreHunter facade to be a true interface to JAMES, with Emun for objectives etc.

**Comment by daveneti** [comment]
created branch feature/facade

**Comment by daveneti** [comment]
Added basic facade. @hdbeukel would you like to have a look. I will add more tests etc when I get time.

**Comment by hdbeukel** [comment]
Looks very good. I have cleaned up some code and added an option to change between parallel tempering (default) and random descent (fast). Also the default stop condition is now dynamic (maximum time without improvement) which I think is better than an absolute runtime limit. See pull request #48.
