### ISSUE TITLE
Fix coverage reports

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#53]
It ssems that the fix in c7b1ea53758291c896523d6909319543b043b91a broke the test coverage reports. Coverage suddenly dropped from 72% to 13% which makes me suspect that the report is broken.

@daveneti Did you notice anything weird with the build?

**Comment by hdbeukel** [comment]
The 13% is the part covered by the integration tests only. Unit test coverage is not reported anymore.

**Comment by hdbeukel** [comment]
I got it working again.

**Comment by daveneti** [comment]
No I did not see anything in the build :( 
At the moment I am stuck on a dependency change that occurred in our recent updates that now stops the RCP GUI for working. I am going to look at old version of CH to find the last one that works.
