### ISSUE TITLE
Consistent default objectives

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#57]
I already built in default objectives in the R package and they are not the same as those recently added to the API in the Java lib (see bb0ac38be423bc1cf654c43942d2001b215a8782, 01b8289ddaf9491d4b71660d6fd0f956324167e0 and b6aa10dc9e9c6e89c7135ff00e12c2d1ab7f4503). I suggest the following defaults (in this order):

1. E-NE with Modified Roger's distance (genotypes)
2. E-NE with Gower's distance (phenotypes)
3. E-NE with precomputed distances

The API now uses A-NE as default distance aggregation and prefers phenotypes over genotypes which I would swap.

@daveneti do you agree that I make these changes?

**Comment by hdbeukel** [comment]
@daveneti Do you plan to enable just one objective by default in the GUI or one per data type (genotypes/phenotypes/distances) as part of a weighted index? Whatever we prefer, we should make sure it the GUI and R interface do the same.

**Comment by daveneti** [comment]
I have added a methods in API on the release\gui-dev branch that provide the default objectives. These are just guesses that the monent. I will align with you decision when i merge back to develop

**Comment by hdbeukel** [comment]
Ok I have currently implemented the defaults from above, in that order of preference when multiple types of data are included. I guess it is better though to default to a weighted index in the latter case (with equal weights) so I will change that.

**Comment by daveneti** [comment]
Hi @hdbeukel, where did you change the defaults? I did not see the changes. In the GUI I use the
`public static final List<CoreHunterObjective> createDefaultObjectives(CoreHunterData coreHunterData)` method to create the default objectives. This creates one default objective for each available type of data. At the moment I am not sure what to do about the weights. I think it does not matter if the sum of the weights is not 1. So dividing by the number of objectives is not important. However, in the interface I think that the weights should be added as an integer summing up to 100. I.e. a percentage, I think this is more easy to understand and edit.

**Comment by hdbeukel** [comment]
I implemented those in the R package which does not (yet) use the new API methods that you added for creating default objectives. I will align both interfaces soon. You are right that the weights do not need to sum to 1. I am ok with your suggestion of summing to 100 in the GUI.

**Comment by daveneti** [comment]
Thanks, my current plan is to keep working on the gui release branch to make minor adaptations needed for the gui, merge this into develop on a regular basis and merge in any of your changes from develop.

**Comment by hdbeukel** [comment]
I pulled in your changes to my branch and updated the default objectives. The tests are now running and then I will merge my branch into develop.
