### ISSUE TITLE
Support for fixed entries in a subset

### ISSUE THREAD

**Issue by daveneti** [corehunter/corehunter3#73]
A common requirement is to fix some entries in a subset, to ensure that certain entries are always selected, regardless of the evaluation.

**Comment by daveneti** [comment]
@hdbeukel is there support for this in JAMES? I have not yet found it. I will look into this once I have completed the GUI.

**Comment by hdbeukel** [comment]
Yes, there is. In the subset neighbourhoods you can specify a set of fixed IDs at construction. These are not modified by any generated move, i.e. if they are currently selected they are not removed, and if they are currently not selected they are not added.

If you want to always select some items, you must make sure though that they are selected in the initial random solution. For now you would have to set a custom random solution generator for the problem, with

```
problem.setRandomSolutionGenerator(...)
```

but I guess I could add a constructor to `SubsetProblem` that takes a set of always selected IDs and defines its solution generator accordingly. That would be for a next version of JAMES though, so I suggest we do this manually for now in Core Hunter. If you want, I can take care of this.

**Comment by daveneti** [comment]
There is no rush on my side, I need to complete the GUI first before starting anything new.

**Comment by hdbeukel** [comment]
I got multiple request for this feature when presenting Core Hunter at the PAG conference just now, so it should be one of the first new features we add. It is not much work.

**Comment by hdbeukel** [comment]
Got a request for this again in the user group. See https://groups.google.com/forum/#!topic/corehunter-users/BSwFBXs5vCs.

**Comment by hdbeukel** [comment]
I also got a request now from IPK Gatersleben for indicating that certain accessions can **not** be selected. At first I thought you would then just reduce the full collection and pretend that the prohibited accessions simply do not exist. But this is only true when maximizing diversity or allelic richness **within** the core. When optimizing representativeness of the full collection (A-NE distance) the accessions that can not be selected actually do provide input for the objective function so cannot simply be ignored.

Luckily this is also supported by JAMES through the fixed ID option so we just need to make sure that we have a valid initial selection then.

I'll get my hands on this issue soon!

**Comment by daveneti** [comment]
Therefore any entry will have one of 4 states:

UNSELECTED
SELECTED
NEVER_SELECTED
ALWAYS_SELECTED

Should we have an enum for this?

**Comment by hdbeukel** [comment]
Sounds as a good idea.

**Comment by daveneti** [comment]
I happy to work on this now that I have fixed quoting issue, shall I?

**Comment by hdbeukel** [comment]
Sure, go ahead!

**Comment by hdbeukel** [comment]
Did you start working on this issue yet? If not, I will do so now.

**Comment by hdbeukel** [comment]
See #94.

**Comment by daveneti** [comment]
No @hdbeukel, did not get time. Too much work at the moment :(

**Comment by hdbeukel** [comment]
No worries. I implemented this yesterday. Tested in Java, not yet in R.
