### ISSUE TITLE
Unquote ids, names and string encoded variable values in phenotype data

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#78]
I noticed that ids and names are not yet unquoted when reading phenotype data from a file. I guess this is an issue in `informatics-commons`? This should be fixed to bring all data types in line.

All values of string encoded variables should be unquoted as well.

**Note:** both single and double quotes should be removed.

**Comment by hdbeukel** [comment]
@daveneti do you prefer me to fix this?

**Comment by daveneti** [comment]
I can't remember the status of this. I will check tonight. I need to make a new release of commons in any case.

**Comment by daveneti** [comment]
Ok, version 1.2.0 now supports quotes, anything within a quote is taken 'as is' including delimiters. The quotes are also removed. Next step is to change make changes in corehunter3 in fearture/ignoreQuotes branch. I will do that tomorrow.

**Comment by hdbeukel** [comment]
Great! If you need any help with updated the read methods of the genotype and distance data let me know. I did the unquoting manually there until now so this could should be removed when using the unquoting option of `TextFileRowReader`.

Remember that the read method for phenotype data is in in the `ArrayFeatureData` class of informatics-common. As far as I can see this one has not been updated yet in the 1.2.0 release?

**Comment by daveneti** [comment]
@hdbeukel I have adapted informatics.common  and release version 1.2.1. I also removed the unquoting, but 3 tests fail. Can you have a look please I do not understand the code. Please note there is no need to add additional cells then the row are uneven, you can use the TextFileRowReader.ROWS_SAME_SIZE option

**Comment by hdbeukel** [comment]
I will have a look. Considering the `ROWS_SAME_SIZE` option: how does it know then how many columns there are? For example one of the supported distance matrix formats only includes the lower diagonal part, like
```
ID
A 0.0
B 0.5 0.0
C 0.2 0.4 0.0
```
How do I tell the reader in advance that there are three four columns here?

**Comment by hdbeukel** [comment]
Looking at your code I understand that `ROWS_SAME_SIZE` expects all lines having the same number of columns as the first one, correct? In that case this only works when column headers are mandatory which is not the case for the distance data or biallelic genotype data. So I guess I cannot use it there. I'll see whether I can use this option to simplify the read methods of the default and frequency genotype data where marker names are mandatory because they indicate the number of columns per marker.

**Comment by daveneti** [comment]
Yep, that is the worse case scenario. At the moment it just checks the first row. I think your code, although may be more inefficient for large dataset is better. I would like to move it to commons, but it was too late last time for me to understand it. If we are not in a rush to change corehunter for the 3.1 release, I would prefer to take some time on this branch re-vamp informatics-common and then update  corehunter3. I would like to do this after 3.1 release, so that I can move forward with the GUI.

**Comment by hdbeukel** [comment]
Allright. I will leave my code that extends the rows untouched then for now. Let me see why the tests fail now and try to fix that. When CH 3.1 has been released I will then also release an update for the R package that handles the unquoting well.

**Comment by daveneti** [comment]
Our comments crossed in the internet. I think it is better to look at updating informatics-commons for what we need in corehunter3. So I suggest not spending any time on this at the moment. Is there a rush? Also we need to look at quoting (or eacaping) again when there is a delimiter in the text.

**Comment by daveneti** [comment]
Sounds like a plan. I will leave this branch open for the 3.2 development, that will use the re-vamped informatics-common code.

**Comment by hdbeukel** [comment]
Great.

**Comment by hdbeukel** [comment]
The failing tests are related to the unquoting. Two things I noticed:

1. Single quotes are not always removed.
2. Non-existing columns are inserted in case of quoted string with whitespace around it.

Many of the test files did not have quotes so I added some more quotes to get a better view of what is going on. Can you pinpoint the issue in informatics-common?

**Comment by daveneti** [comment]
No problem, I will add more tests to informatics-common to pick up the issue. I did have single quote tests, but looks like not enough. I will park this for a 3.2 release.

**Comment by hdbeukel** [comment]
Btw many more tests fail now when adding more quotes.

Example of issue 1: see `biallelic_genotypes/ids-and-names.csv`.
Here the single quotes around `'Alice'` (name) are not removed.

Example of issue 2: see `homozygous_genotypes/ids.csv`.
Here there is an additional column (with value `null`) inserted after `"Eve"` on the last row.

**Comment by hdbeukel** [comment]
I would prefer to fix the unquoting issues right away so that I can also update the R package. Would it be much trouble?

**Comment by daveneti** [comment]
I just have this outstanding deployment bug with corehunter3-ui I want to finally get fixed, so I can do automatic deployments to S3

**Comment by hdbeukel** [comment]
Could you fix that first, then look at the unquoting, then release 3.1?

**Comment by daveneti** [comment]
Yes, that is the plan.

**Comment by daveneti** [comment]
Nearly there, only 3 fails yet to find a solution for.

**Comment by daveneti** [comment]
@hdbeukel can you please look at the last 3 fails. All three are with erroneous files, which are all now passing, whereas before they would fail. You will need to install locally version 1.3.0-SNAPSHOT of informatics-common, which is currently on develop. I will not release this until corehunter is fixed on feature/ignoreQuotes. If you don't time, that is ok, I will look at them again as soon as I have time.

**Comment by hdbeukel** [comment]
I will have a look.

**Comment by hdbeukel** [comment]
For the frequency format, the previously erroneous files that got through are now ok due to your changes to the `ROWS_SAME_SIZE` option. I removed these files from the checks. We have to re-evaluate them later though as the behaviour of this option is going to be further changed in the future (infer number of columns from longest instead of first line).

The remaining fails seems to be due to the file reader discarding empty cells at the beginning of a line (instead of yielding `NULL` there). Any idea why this is happening?

**Comment by daveneti** [comment]
Thanks, I will look at it tonight. I propose not change the ROWS_SAME_SIZE option but adding another option of inferring from the longest line instead, since this new option would result in all data being read, which may not be needed in all cases.

**Comment by hdbeukel** [comment]
Ok I agree with the `ROWS_SAME_SIZE` option. I suggest having two options like `ROWS_SAME_SIZE_AS_FIRST` and `ROWS_SAME_SIZE_AS_LONGEST` then.

**Comment by daveneti** [comment]
That is the plan, I like your names.

**Comment by daveneti** [comment]
fixed and merged into develop
