### ISSUE TITLE
Separate class for default genotype data

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#79]
Having a separate class for the default format that extends the frequency format would e.g. allow to write data (full or subset) to its original format (cfr. biallelic data). Now the default genotype data can only be written to frequency format since it is converted and the original data is not stored.

**Comment by daveneti** [comment]
@hdbeukel the approach I am using is to copy the SimpleGenotypeData class to a new class  SimpleFrequencyGenotypeData. I then removed all the freq related code from SimpleGenotypeData and the non-freq related code from SimpleFrequencyGenotypeData. I removed the read and write method signatures so that they no longer have format as a parameter. I also removed support for writing to frequency for SimpleBiAllelicGenotypeData to be consistent (I will try to think if this a backward step). Now, the next step is to decide on a internal data structure for SimpleGenotypeData. Also to decide if SimpleBiAllelicGenotypeData should extend from  SimpleGenotypeData or SimpleFrequencyGenotypeData, or even to separate it completely. Its getting late here so I will stop and re-think on tomorrow or later in the week. I think that the new internal data structure for SimpleGenotypeData will determine how to proceed so I will work on this. Do you want me to commit the changes so far? Naturally some of the write tests are failing at the moment.

**Comment by hdbeukel** [comment]
Some thoughts:

- Since `FrequencyGenotypeData` is the most general once, and the other two interfaces extend this one, I would suggest the names `BiAllelicGenotypeData` (as is) and `DefaultGenotypeData` (not just `GenotypeData`). It looks weird if `GenotypeData` extends `FrequencyGenotypeData`.
- I think it may be useful to write default/biallelic data in frequency format. So I would keep this functionality, and thus keep format as a parameter for the write methods.
- I was planning to separate biallelic and frequency data for memory efficiency (see #83). I.e. not precompute and store frequencies, which take much more memory than the 0/1/2 matrix, but compute on demand. So `SimpleBiAllelicGenotypeData` would implement both interfaces `BiAllelicGenotypeData` and `FrequencyGenotypeData` but all methods from the latter would have a custom implementation for bi-allelic data, not inherited from frequency data.
- I guess for the default genotype data it makes sense to precompute and store the frequencies since they are much more difficult to infer on demand. Also, default data is already much less compact in terms of memory usage than bi-allelic data, so the relative overhead of also storing the frequencies is lower. Here we have the choice between:
    1. `SimpleDefaultGenotypeData` extends `SimpleFrequencyGenotypeData`.
    2. `SimpleDefaultGenotypeData` encapsulates a `SimpleFrequencyGenotypeData` object.
- The internal data structure of `SimpleDefaultGenotypeData` could simply be a table of `String` values, as provided, no? The only purpose for storing this, is that the original data format remains accessible e.g. for writing output. All calculations are done using the frequencies.

Sure, go ahead and commit.

**Comment by daveneti** [comment]
I won't commit yet because I may revert some of the changes based on your comments above. I will work on this later in the week.

**Comment by daveneti** [comment]
@hdbeukel still not completed this, since my last comment. It is unlikely I will work on this until 2nd week in July. I did some test re-factoring, but I will revert these changes and start from scratch. I will assign it to myself. If you pick it up please re-assign it to yourself.

**Comment by hdbeukel** [comment]
I have time now so I will have a look.

**Comment by hdbeukel** [comment]
We discussed before whether to retain the functionality to write biallelic/default data to frequency format. I was planning to keep this, but now that I am separating simple biallelic data from simple frequency data, for memory efficiency (not precomputing and storing all frequencies), I realize it is not straightforward anymore to write biallelic data to frequency format. This would require a full conversion of the data to frequency format, since it is not readily available.

So let's open the discussion again: how useful is this feature? I suggest to remove it, and if it ever seems needed later, we could consider to re-implement. It has to be recoded anyway due to the refactoring.

**Comment by daveneti** [comment]
I think it is only important to write to the same format as the data is read. Since the user will want the data exported either with an extra 'selected' column or to subset the data that is selected.

**Comment by hdbeukel** [comment]
I have completed the refactoring. Travis build for open source projects are delayed at the moment, so I will wait to merge the pull request until they all checks have completed. Local check run fine though.

For the services module, I resolved all compilation errors, but am not sure whether the new default genotype data class is correctly used there. @daveneti can you check?
