### ISSUE TITLE
Ids or names containing a quote

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#89]
I noticed that some datasets have ids or names containing a quote. For example, the coconut data from Odong et. al ([coconut.csv.zip](https://github.com/corehunter/corehunter3/files/861680/coconut.csv.zip)) contains marker ids like `CnCirH4'` and `CnCir F3'`. Since the last update that fixed quoting issues, trying to read such files produces an error like:

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
```

or for a similar file in frequency format (using suffixes `-1`, `-2`, etc. for naming columns belonging to the same marker, one per allele):

```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException: java.lang.IllegalArgumentException: Invalid marker name at data column 160 (-1,CnCirH4).
```

I guess the reader assumes that delimiters between quotes are part of the row/column names? I also think that is exactly what we want. However, it should work when wrapping the ids containing a single quote in double quotes. Modifying the file accordingly yields

```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException: java.lang.IllegalArgumentException: Duplicate marker name: ”. Columns corresponding to same marker should occur consecutively.
```

The reader now thinks there is a column named `"`. I can't figure out why and I think this should work. @daveneti any ideas?

**Comment by hdbeukel** [comment]
Hmm double quoting the names containing single quotes does seem to work after all, I don't know what went wrong when I tried the first time. Can you confirm that this is how it should work?

**Comment by daveneti** [comment]
double quoting names containing single quotes and vice versa should work. I will add some these to the units tests.

**Comment by daveneti** [comment]
Adding some until tests finds another problem. The writers do not add quotes when the name or id has quotes. So reading them and writing them will cause problems. This is definitely a bug. I will try to fix it when I have time. I expect it will need to be done in the informatics library.

**Comment by daveneti** [comment]
new version informatics-common fixed all this issue.

**Comment by hdbeukel** [comment]
There is an issue with reading data containing quotes in R. See https://github.com/corehunter/corehunter3/pull/92.

**Comment by daveneti** [comment]
@hdbeukel is this still an open issue or is it an issue with the R code?
