### ISSUE TITLE
step-based stop conditions

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#96]
Would it be useful to support step-based stop conditions in addition to the current time-based conditions?

One issue I have experienced with the time-based conditions is that they interfere with reproducibility when setting a seed (see #90). Although the seed eliminates randomness in the sequence of search steps, the number of steps may vary across runs, because the time-based conditions are influenced by external factors such as CPU workload. Therefore, it is not guaranteed that the same solution is returned, unless a "sufficiently" large execution time is allowed.

Using step-based stop conditions would avoid the above issue, so I reckon it may be useful to people aiming at reproducible results.

@daveneti what do you think?

**Comment by daveneti** [comment]
Yes, it is is a good idea.

**Comment by hdbeukel** [comment]
We should think about the most intuitive way for the user to define the number of search steps though, given that "one step" is very different for parallel tempering as compared to random descent. PT executes 500 RD steps within each replica, in a single step of the main search.

Perhaps we should unify/rescale the meaning of "a search step" across both algorithms. This is needed in any case to transfer stop conditions from the main search to the preliminary normalization searches (always RD) in a multi-objective configuration.

I see three options:

  1. Interpret step count `s` in terms of PT and allow `500 * s` steps in RD.
  2. Vice versa, interpret step count `s` in terms of RD and allow `ceil(s/500)` steps in PT.
  3. Interpret step count `s` in terms of the main search (PT or RD, depending on execution mode). I.e. in default mode PT is allowed `s` steps and the RD's for normalization execute `500 * s` steps. In fast mode, both the main RD and the normalization RD's are allowed `s` steps.

Does this make sense to you and which option do you prefer?

**Comment by daveneti** [comment]
I would go for option number 3.

**Comment by hdbeukel** [comment]
@daveneti I implemented these step-based stop conditions (see #102) but they are not yet supported by the services. I will update the R package, could you look at the services?

**Comment by hdbeukel** [comment]
**To do:** think about whether it makes most sense to allow `500 * s` or `10 * 500 * s` steps for RD normalization searches in default mode, since PT executes 500 steps within each of the 10 replicas in each main search step.

**Comment by hdbeukel** [comment]
I decided to stick with `500 * s` because the fact that PT uses 10 replicas is a property of this advanced algorithm and should not be transferred to the RD's used for normalization.
